### ISSUE TITLE
A small problem spawning in the 079 room

### ISSUE THREAD

**Issue by SrLicht** [joker-119/SCP-575#22] opened 2022-03-22 14:36 UTC
When you appear in the 079 room you are inside the room with the computer, so you can't get out.

https://cdn.discordapp.com/attachments/686764908158648341/955836935052595260/SCP_Secret_Laboratory_2022.03.22_-_02.49.21.04.DVR_Trim_Trim.mp4

I tried to upload the video here, but github wouldn't let me :(

**Comment by joker-119** [comment] 2022-03-23 01:29
Duplicate of #21

**Closed by joker-119** 2022-03-23 01:29 UTC
